name: Tag and Build

on:
  push:
    branches:
      - main

env:
  TAG_NAME: ""

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      - name: Set Git default identity
        env:
          GIT_AUTHOR_NAME: ${{ secrets.GIT_AUTHOR_NAME }}
          GIT_AUTHOR_EMAIL: ${{ secrets.GIT_AUTHOR_EMAIL }}
        run: |
          git config --global user.name "$GIT_AUTHOR_NAME"
          git config --global user.email "$GIT_AUTHOR_EMAIL"
          
      - name: Set Tag Name and Build Arg
        run: |
          export COMMIT_MESSAGE=$(git log -1 --pretty=%B)
          export TAG_NAME=$(echo $COMMIT_MESSAGE | grep -oP 'V=[0-9][0-9]?[0-9]?\.[0-9][0-9]?[0-9]?\.[0-9][0-9]?[0-9]?' | tr '[:upper:]' '[:lower:]')
          echo "TAG_NAME=$TAG_NAME"
          export ZXBILD=$(echo $COMMIT_MESSAGE | grep -oP 'ENV=\K\S+')
          echo "ZXBILD=$ZXBILD"
          echo "message=$COMMIT_MESSAGE"
          if [[ ! "$ZXBILD" =~ ^(dev|test|prod)$ ]]; then exit 1; fi
        shell: bash

      - name: Create Tag
        run: |
          export COMMIT_MESSAGE=$(git log -1 --pretty=%B)
          export TAG_MESSAGE=$(echo $COMMIT_MESSAGE | grep -oP 'created tag name V=[0-9][0-9]?[0-9]?\.[0-9][0-9]?[0-9]?\.[0-9][0-9]?[0-9]?' | tr '[:upper:]' '[:lower:]')
          export TAG_NAME=$(echo $COMMIT_MESSAGE | grep -oP 'V=[0-9][0-9]?[0-9]?\.[0-9][0-9]?[0-9]?\.[0-9][0-9]?[0-9]?' | tr '[:upper:]' '[:lower:]')
          git tag -a $TAG_NAME -m "$TAG_MESSAGE"
          git push origin $TAG_NAME

      - name: Build Docker Image
        uses: docker/build-push-action@v2
        with:
          run: |
            docker builder prune --all
          context: .
          build-args: ZXBILD=${ZXBILD}
          push: false
          tags: ${{ env.TAG_NAME }}

      - name: Push Docker Image
        uses: docker/build-push-action@v2
        with:
          context: .
          build-args: ZXBILD=${ZXBILD}
          push: true
          tags: ${{ env.TAG_NAME }}
          registry: docker.pkg.github.com
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
